/** Catálogo de retos de Matiz.
 *
 * Las imágenes y máscaras son PNG locales preparados desde fuentes reales
 * documentadas en apps/web/public/games/matiz/SOURCES.md.
 */
export const MATIZ_CHALLENGES = [
  { id: "popeye-camiseta", title: "Popeye", subtitle: "Pon el color del cuello de Popeye", targetHex: "#ed4754" },
  { id: "pikachu-piel", title: "Pikachu", subtitle: "Pon el color de su piel", targetHex: "#fdd43c" },
  { id: "homer-piel", title: "Homer Simpson", subtitle: "Pon el color de su piel", targetHex: "#ffcd18" },
  { id: "bart-piel", title: "Bart Simpson", subtitle: "Pon el color de su piel", targetHex: "#f6d528" },
  { id: "bob-cuerpo", title: "Bob Esponja", subtitle: "Pon el color de su cuerpo", targetHex: "#fef454" },
  { id: "bulbasaur-piel", title: "Bulbasaur", subtitle: "Pon el color de su piel", targetHex: "#609f80" },
  { id: "charmander-cuerpo", title: "Charmander", subtitle: "Pon el color de su cuerpo", targetHex: "#ed8239" },
  { id: "squirtle-cuerpo", title: "Squirtle", subtitle: "Pon el color de su cuerpo", targetHex: "#70a8ba" },
  { id: "eevee-pelo", title: "Eevee", subtitle: "Pon el color de su pelo", targetHex: "#c38d65" },
  { id: "psyduck-cuerpo", title: "Psyduck", subtitle: "Pon el color de su cuerpo", targetHex: "#eebc41" },
  { id: "pokemon-001-bulbasaur", title: "Bulbasaur", subtitle: "Pon el color de su cuerpo", targetHex: "#91c9ad" },
  { id: "pokemon-002-ivysaur", title: "Ivysaur", subtitle: "Pon el color de su cuerpo", targetHex: "#82b4b9" },
  { id: "pokemon-003-venusaur", title: "Venusaur", subtitle: "Pon el color de su cuerpo", targetHex: "#417f83" },
  { id: "pokemon-004-charmander", title: "Charmander", subtitle: "Pon el color de su cuerpo", targetHex: "#e8aa7d" },
  { id: "pokemon-005-charmeleon", title: "Charmeleon", subtitle: "Pon el color de su cuerpo", targetHex: "#df7e6e" },
  { id: "pokemon-006-charizard", title: "Charizard", subtitle: "Pon el color de su cuerpo", targetHex: "#eda161" },
  { id: "pokemon-007-squirtle", title: "Squirtle", subtitle: "Pon el color de su cuerpo", targetHex: "#669fb1" },
  { id: "pokemon-008-wartortle", title: "Wartortle", subtitle: "Pon el color de su cuerpo", targetHex: "#b9dfeb" },
  { id: "pokemon-009-blastoise", title: "Blastoise", subtitle: "Pon el color de su cuerpo", targetHex: "#715d4f" },
  { id: "pokemon-010-caterpie", title: "Caterpie", subtitle: "Pon el color de su cuerpo", targetHex: "#88c877" },
  { id: "pokemon-011-metapod", title: "Metapod", subtitle: "Pon el color de su cuerpo", targetHex: "#83a651" },
  { id: "pokemon-012-butterfree", title: "Butterfree", subtitle: "Pon el color de su cuerpo", targetHex: "#edf3fb" },
  { id: "pokemon-013-weedle", title: "Weedle", subtitle: "Pon el color de su cuerpo", targetHex: "#ae8457" },
  { id: "pokemon-014-kakuna", title: "Kakuna", subtitle: "Pon el color de su cuerpo", targetHex: "#d3bb69" },
  { id: "pokemon-015-beedrill", title: "Beedrill", subtitle: "Pon el color de su cuerpo", targetHex: "#e3e7ee" },
  { id: "pokemon-016-pidgey", title: "Pidgey", subtitle: "Pon el color de su cuerpo", targetHex: "#bc9561" },
  { id: "pokemon-017-pidgeotto", title: "Pidgeotto", subtitle: "Pon el color de su cuerpo", targetHex: "#c5b992" },
  { id: "pokemon-018-pidgeot", title: "Pidgeot", subtitle: "Pon el color de su cuerpo", targetHex: "#cec39e" },
  { id: "pokemon-019-rattata", title: "Rattata", subtitle: "Pon el color de su cuerpo", targetHex: "#a083ab" },
  { id: "pokemon-020-raticate", title: "Raticate", subtitle: "Pon el color de su cuerpo", targetHex: "#94693a" },
  { id: "pokemon-021-spearow", title: "Spearow", subtitle: "Pon el color de su cuerpo", targetHex: "#905f49" },
  { id: "pokemon-022-fearow", title: "Fearow", subtitle: "Pon el color de su cuerpo", targetHex: "#aa784e" },
  { id: "pokemon-023-ekans", title: "Ekans", subtitle: "Pon el color de su cuerpo", targetHex: "#88607f" },
  { id: "pokemon-024-arbok", title: "Arbok", subtitle: "Pon el color de su cuerpo", targetHex: "#8e8394" },
  { id: "pokemon-025-pikachu", title: "Pikachu", subtitle: "Pon el color de su cuerpo", targetHex: "#e2c270" },
  { id: "pokemon-026-raichu", title: "Raichu", subtitle: "Pon el color de su cuerpo", targetHex: "#fbf1db" },
  { id: "pokemon-027-sandshrew", title: "Sandshrew", subtitle: "Pon el color de su cuerpo", targetHex: "#e9ca7a" },
  { id: "pokemon-028-sandslash", title: "Sandslash", subtitle: "Pon el color de su cuerpo", targetHex: "#e3c06d" },
  { id: "pokemon-029-nidoran-f", title: "Nidoran♀", subtitle: "Pon el color de su cuerpo", targetHex: "#bfcde8" },
  { id: "pokemon-030-nidorina", title: "Nidorina", subtitle: "Pon el color de su cuerpo", targetHex: "#c2d9de" },
  { id: "pokemon-031-nidoqueen", title: "Nidoqueen", subtitle: "Pon el color de su cuerpo", targetHex: "#658daf" },
  { id: "pokemon-032-nidoran-m", title: "Nidoran♂", subtitle: "Pon el color de su cuerpo", targetHex: "#9d729e" },
  { id: "pokemon-033-nidorino", title: "Nidorino", subtitle: "Pon el color de su cuerpo", targetHex: "#907191" },
  { id: "pokemon-034-nidoking", title: "Nidoking", subtitle: "Pon el color de su cuerpo", targetHex: "#af80af" },
  { id: "pokemon-035-clefairy", title: "Clefairy", subtitle: "Pon el color de su cuerpo", targetHex: "#f9d0d4" },
  { id: "pokemon-036-clefable", title: "Clefable", subtitle: "Pon el color de su cuerpo", targetHex: "#f4dad2" },
  { id: "pokemon-037-vulpix", title: "Vulpix", subtitle: "Pon el color de su cuerpo", targetHex: "#c28770" },
  { id: "pokemon-038-ninetales", title: "Ninetales", subtitle: "Pon el color de su cuerpo", targetHex: "#f0e4a1" },
  { id: "pokemon-039-jigglypuff", title: "Jigglypuff", subtitle: "Pon el color de su cuerpo", targetHex: "#f3ced7" },
  { id: "pokemon-040-wigglytuff", title: "Wigglytuff", subtitle: "Pon el color de su cuerpo", targetHex: "#f4eef3" },
  { id: "pokemon-041-zubat", title: "Zubat", subtitle: "Pon el color de su cuerpo", targetHex: "#a46ea6" },
  { id: "pokemon-042-golbat", title: "Golbat", subtitle: "Pon el color de su cuerpo", targetHex: "#ac6fae" },
  { id: "pokemon-043-oddish", title: "Oddish", subtitle: "Pon el color de su cuerpo", targetHex: "#51a946" },
  { id: "pokemon-044-gloom", title: "Gloom", subtitle: "Pon el color de su cuerpo", targetHex: "#8a5146" },
  { id: "pokemon-045-vileplume", title: "Vileplume", subtitle: "Pon el color de su cuerpo", targetHex: "#df99a5" },
  { id: "pokemon-046-paras", title: "Paras", subtitle: "Pon el color de su cuerpo", targetHex: "#ea9b5f" },
  { id: "pokemon-047-parasect", title: "Parasect", subtitle: "Pon el color de su cuerpo", targetHex: "#be8051" },
  { id: "pokemon-048-venonat", title: "Venonat", subtitle: "Pon el color de su cuerpo", targetHex: "#5e588e" },
  { id: "pokemon-049-venomoth", title: "Venomoth", subtitle: "Pon el color de su cuerpo", targetHex: "#e4d9ec" },
  { id: "pokemon-050-diglett", title: "Diglett", subtitle: "Pon el color de su cuerpo", targetHex: "#a98a78" },
  { id: "pokemon-051-dugtrio", title: "Dugtrio", subtitle: "Pon el color de su cuerpo", targetHex: "#9e8170" },
  { id: "pokemon-052-meowth", title: "Meowth", subtitle: "Pon el color de su cuerpo", targetHex: "#f4ebce" },
  { id: "pokemon-053-persian", title: "Persian", subtitle: "Pon el color de su cuerpo", targetHex: "#f2dfb7" },
  { id: "pokemon-054-psyduck", title: "Psyduck", subtitle: "Pon el color de su cuerpo", targetHex: "#ddb878" },
  { id: "pokemon-055-golduck", title: "Golduck", subtitle: "Pon el color de su cuerpo", targetHex: "#80afd2" },
  { id: "pokemon-056-mankey", title: "Mankey", subtitle: "Pon el color de su cuerpo", targetHex: "#f4e3d5" },
  { id: "pokemon-057-primeape", title: "Primeape", subtitle: "Pon el color de su cuerpo", targetHex: "#f2e0d1" },
  { id: "pokemon-058-growlithe", title: "Growlithe", subtitle: "Pon el color de su cuerpo", targetHex: "#f0d9b9" },
  { id: "pokemon-059-arcanine", title: "Arcanine", subtitle: "Pon el color de su cuerpo", targetHex: "#cfb8a1" },
  { id: "pokemon-060-poliwag", title: "Poliwag", subtitle: "Pon el color de su cuerpo", targetHex: "#5777a0" },
  { id: "pokemon-061-poliwhirl", title: "Poliwhirl", subtitle: "Pon el color de su cuerpo", targetHex: "#dce2ef" },
  { id: "pokemon-062-poliwrath", title: "Poliwrath", subtitle: "Pon el color de su cuerpo", targetHex: "#55759d" },
  { id: "pokemon-063-abra", title: "Abra", subtitle: "Pon el color de su cuerpo", targetHex: "#f0d658" },
  { id: "pokemon-064-kadabra", title: "Kadabra", subtitle: "Pon el color de su cuerpo", targetHex: "#efd357" },
  { id: "pokemon-065-alakazam", title: "Alakazam", subtitle: "Pon el color de su cuerpo", targetHex: "#ead156" },
  { id: "pokemon-066-machop", title: "Machop", subtitle: "Pon el color de su cuerpo", targetHex: "#a7c6cf" },
  { id: "pokemon-067-machoke", title: "Machoke", subtitle: "Pon el color de su cuerpo", targetHex: "#a9b0ce" },
  { id: "pokemon-068-machamp", title: "Machamp", subtitle: "Pon el color de su cuerpo", targetHex: "#9eb2c4" },
  { id: "pokemon-069-bellsprout", title: "Bellsprout", subtitle: "Pon el color de su cuerpo", targetHex: "#eceb70" },
  { id: "pokemon-070-weepinbell", title: "Weepinbell", subtitle: "Pon el color de su cuerpo", targetHex: "#89ca8f" },
  { id: "pokemon-071-victreebel", title: "Victreebel", subtitle: "Pon el color de su cuerpo", targetHex: "#88ca8e" },
  { id: "pokemon-072-tentacool", title: "Tentacool", subtitle: "Pon el color de su cuerpo", targetHex: "#6dbee1" },
  { id: "pokemon-073-tentacruel", title: "Tentacruel", subtitle: "Pon el color de su cuerpo", targetHex: "#a9a299" },
  { id: "pokemon-074-geodude", title: "Geodude", subtitle: "Pon el color de su cuerpo", targetHex: "#b3b1a9" },
  { id: "pokemon-075-graveler", title: "Graveler", subtitle: "Pon el color de su cuerpo", targetHex: "#c8c8be" },
  { id: "pokemon-076-golem", title: "Golem", subtitle: "Pon el color de su cuerpo", targetHex: "#585451" },
  { id: "pokemon-077-ponyta", title: "Ponyta", subtitle: "Pon el color de su cuerpo", targetHex: "#e9dfb8" },
  { id: "pokemon-078-rapidash", title: "Rapidash", subtitle: "Pon el color de su cuerpo", targetHex: "#f2e9c2" },
  { id: "pokemon-079-slowpoke", title: "Slowpoke", subtitle: "Pon el color de su cuerpo", targetHex: "#e3a5b7" },
  { id: "pokemon-080-slowbro", title: "Slowbro", subtitle: "Pon el color de su cuerpo", targetHex: "#c7939f" },
  { id: "pokemon-081-magnemite", title: "Magnemite", subtitle: "Pon el color de su cuerpo", targetHex: "#a0c1ca" },
  { id: "pokemon-082-magneton", title: "Magneton", subtitle: "Pon el color de su cuerpo", targetHex: "#909092" },
  { id: "pokemon-083-farfetchd", title: "Farfetch’d", subtitle: "Pon el color de su cuerpo", targetHex: "#9f8f8b" },
  { id: "pokemon-084-doduo", title: "Doduo", subtitle: "Pon el color de su cuerpo", targetHex: "#a97f65" },
  { id: "pokemon-085-dodrio", title: "Dodrio", subtitle: "Pon el color de su cuerpo", targetHex: "#9b7766" },
  { id: "pokemon-086-seel", title: "Seel", subtitle: "Pon el color de su cuerpo", targetHex: "#e0e8f2" },
  { id: "pokemon-087-dewgong", title: "Dewgong", subtitle: "Pon el color de su cuerpo", targetHex: "#ecf2f7" },
  { id: "pokemon-088-grimer", title: "Grimer", subtitle: "Pon el color de su cuerpo", targetHex: "#8e7a96" },
  { id: "pokemon-089-muk", title: "Muk", subtitle: "Pon el color de su cuerpo", targetHex: "#a897b2" },
  { id: "pokemon-090-shellder", title: "Shellder", subtitle: "Pon el color de su cuerpo", targetHex: "#837fb8" },
  { id: "pokemon-091-cloyster", title: "Cloyster", subtitle: "Pon el color de su cuerpo", targetHex: "#9088a8" },
  { id: "pokemon-092-gastly", title: "Gastly", subtitle: "Pon el color de su cuerpo", targetHex: "#927691" },
  { id: "pokemon-093-haunter", title: "Haunter", subtitle: "Pon el color de su cuerpo", targetHex: "#584e5e" },
  { id: "pokemon-094-gengar", title: "Gengar", subtitle: "Pon el color de su cuerpo", targetHex: "#7f7aa4" },
  { id: "pokemon-095-onix", title: "Onix", subtitle: "Pon el color de su cuerpo", targetHex: "#a1a0aa" },
  { id: "pokemon-096-drowzee", title: "Drowzee", subtitle: "Pon el color de su cuerpo", targetHex: "#eec64a" },
  { id: "pokemon-097-hypno", title: "Hypno", subtitle: "Pon el color de su cuerpo", targetHex: "#f8d954" },
  { id: "pokemon-098-krabby", title: "Krabby", subtitle: "Pon el color de su cuerpo", targetHex: "#f19868" },
  { id: "pokemon-099-kingler", title: "Kingler", subtitle: "Pon el color de su cuerpo", targetHex: "#c17b58" },
  { id: "pokemon-100-voltorb", title: "Voltorb", subtitle: "Pon el color de su cuerpo", targetHex: "#e18d88" },
  { id: "cartoon-sonic", title: "Sonic", subtitle: "Pon el color de su cuerpo", targetHex: "#00207e" },
  { id: "cartoon-mickey", title: "Mickey Mouse", subtitle: "Pon el color de su pantalón", targetHex: "#da222e" },
  { id: "cartoon-pacman", title: "Pac-Man", subtitle: "Pon el color del personaje", targetHex: "#f2f000" },
  { id: "cartoon-mario", title: "Mario", subtitle: "Pon el color de su pantalón", targetHex: "#124eae" },
  { id: "cartoon-crash", title: "Crash Bandicoot", subtitle: "Pon el color de su pelo", targetHex: "#e85412" },
  { id: "cartoon-kirby", title: "Kirby", subtitle: "Pon el color de su cuerpo", targetHex: "#ff5881" },
  { id: "cartoon-bugs-bunny", title: "Bugs Bunny", subtitle: "Pon el color de su cuerpo", targetHex: "#afb3b6" },
  { id: "cartoon-tom-jerry", title: "Tom y Jerry", subtitle: "Pon el color de Tom", targetHex: "#505050" },
  { id: "logo-png-google", title: "Google", subtitle: "Pon el color del logo", targetHex: "#4085f3" },
  { id: "logo-png-youtube", title: "YouTube", subtitle: "Pon el color del logo", targetHex: "#ff0000" },
  { id: "logo-png-netflix", title: "Netflix", subtitle: "Pon el color del logo", targetHex: "#d82126" },
  { id: "logo-png-mcdonalds", title: "McDonald’s", subtitle: "Pon el color del logo", targetHex: "#ffc500" },
  { id: "logo-png-nike", title: "Nike", subtitle: "Pon el color del logo", targetHex: "#000000" },
  { id: "toon-simpsons-marge-hair", title: "Marge Simpson", subtitle: "Pon el color de su pelo", targetHex: "#2373b0" },
  { id: "toon-simpsons-bart-shirt", title: "Bart Simpson", subtitle: "Pon el color de su camiseta", targetHex: "#f46924" },
  { id: "toon-simpsons-bart-shorts", title: "Bart Simpson", subtitle: "Pon el color de sus pantalones", targetHex: "#3666b6" },
  { id: "toon-simpsons-lisa-dress", title: "Lisa Simpson", subtitle: "Pon el color de su vestido", targetHex: "#e12d34" },
  { id: "toon-simpsons-maggie-outfit", title: "Maggie Simpson", subtitle: "Pon el color de su ropa", targetHex: "#5ca0d6" },
  { id: "toon-simpsons-homer-pants", title: "Homer Simpson", subtitle: "Pon el color de sus pantalones", targetHex: "#3666b6" },
  { id: "toon-simpsons-marge-dress", title: "Marge Simpson", subtitle: "Pon el color de su vestido", targetHex: "#5baa56" },
  { id: "toon-futurama-leela-hair", title: "Leela · Futurama", subtitle: "Pon el color de su pelo", targetHex: "#7d3192" },
  { id: "toon-futurama-fry-jacket", title: "Fry · Futurama", subtitle: "Pon el color de su chaqueta", targetHex: "#b42629" },
  { id: "toon-futurama-bender-body", title: "Bender · Futurama", subtitle: "Pon el color de su cuerpo", targetHex: "#9da19e" },
  { id: "toon-family-guy-peter-pants", title: "Peter Griffin", subtitle: "Pon el color de sus pantalones", targetHex: "#549643" },
  { id: "toon-family-guy-lois-blouse", title: "Lois Griffin", subtitle: "Pon el color de su camiseta", targetHex: "#389885" },
  { id: "toon-family-guy-meg-shirt", title: "Meg Griffin", subtitle: "Pon el color de su camiseta", targetHex: "#e994b4" },
  { id: "toon-family-guy-chris-shirt", title: "Chris Griffin", subtitle: "Pon el color de su camiseta", targetHex: "#4884ca" },
  { id: "toon-family-guy-stewie-overalls", title: "Stewie Griffin", subtitle: "Pon el color de su ropa", targetHex: "#d22627" },
  { id: "toon-family-guy-brian-collar", title: "Brian Griffin", subtitle: "Pon el color de su collar", targetHex: "#d52d2a" },
  { id: "toon-sponge-body", title: "Bob Esponja", subtitle: "Pon el color de su cuerpo", targetHex: "#f7e02e" },
  { id: "toon-sponge-patrick-shorts", title: "Patricio Estrella", subtitle: "Pon el color de sus pantalones", targetHex: "#6fb254" },
  { id: "toon-sponge-patrick-body", title: "Patricio Estrella", subtitle: "Pon el color de su cuerpo", targetHex: "#ef97a6" },
  { id: "toon-sponge-squidward-shirt", title: "Calamardo", subtitle: "Pon el color de su camiseta", targetHex: "#a86c66" },
  { id: "toon-sponge-sandy-suit", title: "Arenita", subtitle: "Pon el color de su traje", targetHex: "#f5f5ee" },
  { id: "toon-adventure-finn-shirt", title: "Finn · Hora de Aventuras", subtitle: "Pon el color de su camiseta", targetHex: "#348fd0" },
  { id: "toon-adventure-finn-backpack", title: "Finn · Hora de Aventuras", subtitle: "Pon el color de su mochila", targetHex: "#4fa147" },
  { id: "toon-adventure-finn-shorts", title: "Finn · Hora de Aventuras", subtitle: "Pon el color de sus pantalones", targetHex: "#1f56a1" },
  { id: "toon-adventure-jake-body", title: "Jake · Hora de Aventuras", subtitle: "Pon el color de su cuerpo", targetHex: "#f7cf2d" },
  { id: "toon-rick-hair", title: "Rick Sanchez", subtitle: "Pon el color de su pelo", targetHex: "#71c2da" },
  { id: "toon-rick-coat", title: "Rick Sanchez", subtitle: "Pon el color de su bata", targetHex: "#f5f5f0" },
  { id: "toon-morty-shirt", title: "Morty Smith", subtitle: "Pon el color de su camiseta", targetHex: "#f1cb36" },
  { id: "toon-morty-pants", title: "Morty Smith", subtitle: "Pon el color de sus pantalones", targetHex: "#4069b4" },
  { id: "toon-southpark-cartman-jacket", title: "Eric Cartman", subtitle: "Pon el color de su chaqueta", targetHex: "#d72d26" },
  { id: "toon-southpark-stan-hat", title: "Stan Marsh", subtitle: "Pon el color de su gorro", targetHex: "#2f63be" },
  { id: "toon-southpark-kyle-hat", title: "Kyle Broflovski", subtitle: "Pon el color de su gorro", targetHex: "#40913d" },
  { id: "toon-southpark-kenny-parka", title: "Kenny McCormick", subtitle: "Pon el color de su parka", targetHex: "#ee7326" },
  { id: "toon-southpark-cartman-gloves", title: "Eric Cartman", subtitle: "Pon el color de sus guantes", targetHex: "#f6c72d" },
  { id: "toon-shrek-skin", title: "Shrek", subtitle: "Pon el color de su piel", targetHex: "#6f973a" },
  { id: "toon-shrek-fiona-dress", title: "Fiona · Shrek", subtitle: "Pon el color de su vestido", targetHex: "#4b9b52" },
  { id: "toon-shrek-donkey-body", title: "Burro · Shrek", subtitle: "Pon el color de su cuerpo", targetHex: "#717168" },
  { id: "toon-shrek-puss-hat", title: "Gato con Botas", subtitle: "Pon el color de su gorro", targetHex: "#2b529d" },
  { id: "toon-looney-daffy-body", title: "Pato Lucas", subtitle: "Pon el color de su cuerpo", targetHex: "#23262a" },
  { id: "toon-looney-tweety-body", title: "Piolín", subtitle: "Pon el color de su cuerpo", targetHex: "#f7de34" },
  { id: "toon-looney-sylvester-body", title: "Silvestre", subtitle: "Pon el color de su cuerpo", targetHex: "#73787e" },
  { id: "logo-extra-adidas", title: "Adidas", subtitle: "Pon el color del logo", targetHex: "#000000" },
  { id: "logo-extra-amazon", title: "Amazon", subtitle: "Pon el color del logo", targetHex: "#ff9900" },
  { id: "logo-extra-apple", title: "Apple", subtitle: "Pon el color del logo", targetHex: "#000000" },
  { id: "logo-extra-coca-cola", title: "Coca-Cola", subtitle: "Pon el color del logo", targetHex: "#e61d2b" },
  { id: "logo-extra-facebook", title: "Facebook", subtitle: "Pon el color del logo", targetHex: "#1977f3" },
  { id: "logo-extra-futurama", title: "Futurama", subtitle: "Pon el color del logo", targetHex: "#f7f06f" },
  { id: "logo-extra-instagram", title: "Instagram", subtitle: "Pon el color del logo", targetHex: "#fc01d7" },
  { id: "logo-extra-linkedin", title: "LinkedIn", subtitle: "Pon el color del logo", targetHex: "#0a66c2" },
  { id: "logo-extra-nintendo", title: "Nintendo", subtitle: "Pon el color del logo", targetHex: "#ed1c24" },
  { id: "logo-extra-playstation", title: "PlayStation", subtitle: "Pon el color del logo", targetHex: "#000000" },
  { id: "logo-extra-reddit", title: "Reddit", subtitle: "Pon el color del logo", targetHex: "#ff4500" },
  { id: "logo-extra-spotify", title: "Spotify", subtitle: "Pon el color del logo", targetHex: "#1ed760" },
  { id: "logo-extra-telegram", title: "Telegram", subtitle: "Pon el color del logo", targetHex: "#30a8de" },
  { id: "logo-extra-simpsons", title: "Los Simpson", subtitle: "Pon el color del logo", targetHex: "#ffde00" },
  { id: "logo-extra-whatsapp", title: "WhatsApp", subtitle: "Pon el color del logo", targetHex: "#48c857" },
  { id: "logo-extra-bmw", title: "BMW", subtitle: "Pon el color del logo", targetHex: "#f2f2f2" },
  { id: "logo-extra-burger-king", title: "Burger King", subtitle: "Pon el color del logo", targetHex: "#ee1d22" },
  { id: "logo-extra-epic-games", title: "Epic Games", subtitle: "Pon el color del logo", targetHex: "#2f2d2e" },
  { id: "logo-extra-lego", title: "LEGO", subtitle: "Pon el color del logo", targetHex: "#e3000b" },
  { id: "logo-extra-mercedes", title: "Mercedes-Benz", subtitle: "Pon el color del logo", targetHex: "#313e46" },
  { id: "logo-extra-microsoft", title: "Microsoft", subtitle: "Pon el color del logo", targetHex: "#ffba08" },
  { id: "logo-extra-nintendo-switch", title: "Nintendo Switch", subtitle: "Pon el color del logo", targetHex: "#000000" },
  { id: "logo-extra-pepsi", title: "Pepsi", subtitle: "Pon el color del logo", targetHex: "#0e0e96" },
  { id: "logo-extra-roblox", title: "Roblox", subtitle: "Pon el color del logo", targetHex: "#000000" },
  { id: "logo-extra-steam", title: "Steam", subtitle: "Pon el color del logo", targetHex: "#c2c1bf" },
  { id: "logo-extra-toyota", title: "Toyota", subtitle: "Pon el color del logo", targetHex: "#eb0a1e" },
  { id: "logo-extra-angry-birds", title: "Angry Birds", subtitle: "Pon el color del logo", targetHex: "#000000" },
  { id: "logo-extra-call-of-duty", title: "Call of Duty", subtitle: "Pon el color del logo", targetHex: "#000000" },
  { id: "logo-extra-counter-strike-2", title: "Counter-Strike 2", subtitle: "Pon el color del logo", targetHex: "#1e202f" },
  { id: "logo-extra-dc-comics", title: "DC Comics", subtitle: "Pon el color del logo", targetHex: "#0376f2" },
  { id: "logo-extra-disney", title: "Disney", subtitle: "Pon el color del logo", targetHex: "#000000" },
  { id: "logo-extra-marvel", title: "Marvel", subtitle: "Pon el color del logo", targetHex: "#ed1d24" },
  { id: "logo-extra-overwatch-2", title: "Overwatch 2", subtitle: "Pon el color del logo", targetHex: "#333f49" },
  { id: "logo-extra-pixar", title: "Pixar", subtitle: "Pon el color del logo", targetHex: "#000000" },
  { id: "logo-extra-sonic-logo", title: "Sonic the Hedgehog", subtitle: "Pon el color del logo", targetHex: "#001478" },
  { id: "logo-extra-star-wars", title: "Star Wars", subtitle: "Pon el color del logo", targetHex: "#fee81f" },
  { id: "logo-extra-valorant", title: "Valorant", subtitle: "Pon el color del logo", targetHex: "#000000" },
  { id: "logo-extra-dora-explorer", title: "Dora la Exploradora", subtitle: "Pon el color del logo", targetHex: "#f13ea1" },
  { id: "logo-extra-family-guy", title: "Padre de Familia", subtitle: "Pon el color del logo", targetHex: "#00a0d4" },
  { id: "logo-extra-looney-tunes", title: "Looney Tunes", subtitle: "Pon el color del logo", targetHex: "#cf0f2e" },
  { id: "logo-extra-naruto", title: "Naruto", subtitle: "Pon el color del logo", targetHex: "#ec4b88" },
  { id: "logo-extra-pocoyo", title: "Pocoyó", subtitle: "Pon el color del logo", targetHex: "#e15e34" },
  { id: "logo-extra-south-park", title: "South Park", subtitle: "Pon el color del logo", targetHex: "#000000" },
  { id: "logo-extra-flintstones", title: "Los Picapiedra", subtitle: "Pon el color del logo", targetHex: "#cc0000" },
  { id: "logo-extra-powerpuff-girls", title: "Las Supernenas", subtitle: "Pon el color del logo", targetHex: "#f471b4" },
  { id: "logo-extra-tom-and-jerry", title: "Tom y Jerry", subtitle: "Pon el color del logo", targetHex: "#e1393e" },
  { id: "logo-extra-warner-bros", title: "Warner Bros.", subtitle: "Pon el color del logo", targetHex: "#0541a8" },
  { id: "logo-extra-android", title: "Android", subtitle: "Pon el color del logo", targetHex: "#32de84" },
  { id: "logo-extra-gitlab", title: "GitLab", subtitle: "Pon el color del logo", targetHex: "#8c929d" },
  { id: "logo-extra-gmail", title: "Gmail", subtitle: "Pon el color del logo", targetHex: "#ea4335" },
  { id: "logo-extra-chrome", title: "Google Chrome", subtitle: "Pon el color del logo", targetHex: "#ffcd43" },
  { id: "logo-extra-nasa", title: "NASA", subtitle: "Pon el color del logo", targetHex: "#0b3d91" },
  { id: "logo-extra-opera", title: "Opera", subtitle: "Pon el color del logo", targetHex: "#ff1b2d" },
  { id: "logo-extra-slack", title: "Slack", subtitle: "Pon el color del logo", targetHex: "#2eb67d" },
  { id: "logo-extra-spacex", title: "SpaceX", subtitle: "Pon el color del logo", targetHex: "#005288" },
  { id: "logo-extra-stack-overflow", title: "Stack Overflow", subtitle: "Pon el color del logo", targetHex: "#f48023" },
  { id: "logo-extra-twitch", title: "Twitch", subtitle: "Pon el color del logo", targetHex: "#6441a5" },
  { id: "logo-extra-champions-league", title: "Champions League", subtitle: "Pon el color del logo", targetHex: "#00004b" },
  { id: "logo-extra-windows", title: "Windows", subtitle: "Pon el color del logo", targetHex: "#0078d4" },
] as const;

export type MatizChallengeId = (typeof MATIZ_CHALLENGES)[number]['id'];

export function matizChallengeById(id: string) {
  return MATIZ_CHALLENGES.find((challenge) => challenge.id === id) ?? MATIZ_CHALLENGES[0];
}
