import type { PriceQuestion } from './content.ts';

/**
 * Catálogo offline generado una vez para que Precio justo funcione sin API ni
 * credenciales. Las imágenes viven en apps/web/public y el precio queda
 * congelado dentro de cada pregunta.
 */
export const OFFLINE_PRICE_QUESTIONS = [
  {
    "id": "offline-1",
    "title": "Essence Mascara Lash Princess",
    "image": "/games/preciojusto/catalog/001-essence-mascara-lash-princess.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/1",
    "category": "curiosos",
    "brandModel": "Essence",
    "variant": "Essence · Belleza · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 999,
    "seller": "Essence",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-2",
    "title": "Eyeshadow Palette with Mirror",
    "image": "/games/preciojusto/catalog/002-eyeshadow-palette-with-mirror.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/2",
    "category": "curiosos",
    "brandModel": "Glamour Beauty",
    "variant": "Glamour Beauty · Belleza · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1999,
    "seller": "Glamour Beauty",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-3",
    "title": "Powder Canister",
    "image": "/games/preciojusto/catalog/003-powder-canister.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/3",
    "category": "curiosos",
    "brandModel": "Velvet Touch",
    "variant": "Velvet Touch · Belleza · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1499,
    "seller": "Velvet Touch",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-4",
    "title": "Red Lipstick",
    "image": "/games/preciojusto/catalog/004-red-lipstick.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/4",
    "category": "curiosos",
    "brandModel": "Chic Cosmetics",
    "variant": "Chic Cosmetics · Belleza · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1299,
    "seller": "Chic Cosmetics",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-5",
    "title": "Red Nail Polish",
    "image": "/games/preciojusto/catalog/005-red-nail-polish.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/5",
    "category": "curiosos",
    "brandModel": "Nail Couture",
    "variant": "Nail Couture · Belleza · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 899,
    "seller": "Nail Couture",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-6",
    "title": "Calvin Klein CK One",
    "image": "/games/preciojusto/catalog/006-calvin-klein-ck-one.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/6",
    "category": "curiosos",
    "brandModel": "Calvin Klein",
    "variant": "Calvin Klein · Perfumería · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 4999,
    "seller": "Calvin Klein",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-7",
    "title": "Chanel Coco Noir Eau De",
    "image": "/games/preciojusto/catalog/007-chanel-coco-noir-eau-de.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/7",
    "category": "curiosos",
    "brandModel": "Chanel",
    "variant": "Chanel · Perfumería · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 12999,
    "seller": "Chanel",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-8",
    "title": "Dior J'adore",
    "image": "/games/preciojusto/catalog/008-dior-j-adore.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/8",
    "category": "curiosos",
    "brandModel": "Dior",
    "variant": "Dior · Perfumería · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 8999,
    "seller": "Dior",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-9",
    "title": "Dolce Shine Eau de",
    "image": "/games/preciojusto/catalog/009-dolce-shine-eau-de.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/9",
    "category": "curiosos",
    "brandModel": "Dolce & Gabbana",
    "variant": "Dolce & Gabbana · Perfumería · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 6999,
    "seller": "Dolce & Gabbana",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-10",
    "title": "Gucci Bloom Eau de",
    "image": "/games/preciojusto/catalog/010-gucci-bloom-eau-de.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/10",
    "category": "curiosos",
    "brandModel": "Gucci",
    "variant": "Gucci · Perfumería · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 7999,
    "seller": "Gucci",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-11",
    "title": "Annibale Colombo Bed",
    "image": "/games/preciojusto/catalog/011-annibale-colombo-bed.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/11",
    "category": "hogar",
    "brandModel": "Annibale Colombo",
    "variant": "Annibale Colombo · Muebles · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 189999,
    "seller": "Annibale Colombo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-12",
    "title": "Annibale Colombo Sofa",
    "image": "/games/preciojusto/catalog/012-annibale-colombo-sofa.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/12",
    "category": "hogar",
    "brandModel": "Annibale Colombo",
    "variant": "Annibale Colombo · Muebles · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 249999,
    "seller": "Annibale Colombo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-13",
    "title": "Bedside Table African Cherry",
    "image": "/games/preciojusto/catalog/013-bedside-table-african-cherry.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/13",
    "category": "hogar",
    "brandModel": "Furniture Co.",
    "variant": "Furniture Co. · Muebles · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 29999,
    "seller": "Furniture Co.",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-14",
    "title": "Knoll Saarinen Executive Conference Chair",
    "image": "/games/preciojusto/catalog/014-knoll-saarinen-executive-conference-chair.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/14",
    "category": "hogar",
    "brandModel": "Knoll",
    "variant": "Knoll · Muebles · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 49999,
    "seller": "Knoll",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-15",
    "title": "Wooden Bathroom Sink With Mirror",
    "image": "/games/preciojusto/catalog/015-wooden-bathroom-sink-with-mirror.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/15",
    "category": "hogar",
    "brandModel": "Bath Trends",
    "variant": "Bath Trends · Muebles · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 79999,
    "seller": "Bath Trends",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-16",
    "title": "Apple",
    "image": "/games/preciojusto/catalog/016-apple.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/16",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 199,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-17",
    "title": "Beef Steak",
    "image": "/games/preciojusto/catalog/017-beef-steak.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/17",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1299,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-18",
    "title": "Cat Food",
    "image": "/games/preciojusto/catalog/018-cat-food.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/18",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 899,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-19",
    "title": "Chicken Meat",
    "image": "/games/preciojusto/catalog/019-chicken-meat.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/19",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 999,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-20",
    "title": "Cooking Oil",
    "image": "/games/preciojusto/catalog/020-cooking-oil.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/20",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 499,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-21",
    "title": "Cucumber",
    "image": "/games/preciojusto/catalog/021-cucumber.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/21",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 149,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-22",
    "title": "Dog Food",
    "image": "/games/preciojusto/catalog/022-dog-food.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/22",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1099,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-23",
    "title": "Eggs",
    "image": "/games/preciojusto/catalog/023-eggs.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/23",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 299,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-24",
    "title": "Fish Steak",
    "image": "/games/preciojusto/catalog/024-fish-steak.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/24",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1499,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-25",
    "title": "Green Bell Pepper",
    "image": "/games/preciojusto/catalog/025-green-bell-pepper.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/25",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 129,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-26",
    "title": "Green Chili Pepper",
    "image": "/games/preciojusto/catalog/026-green-chili-pepper.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/26",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 99,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-27",
    "title": "Honey Jar",
    "image": "/games/preciojusto/catalog/027-honey-jar.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/27",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 699,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-28",
    "title": "Ice Cream",
    "image": "/games/preciojusto/catalog/028-ice-cream.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/28",
    "category": "ocio",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 549,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-29",
    "title": "Juice",
    "image": "/games/preciojusto/catalog/029-juice.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/29",
    "category": "ocio",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 399,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-30",
    "title": "Kiwi",
    "image": "/games/preciojusto/catalog/030-kiwi.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/30",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 249,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-31",
    "title": "Lemon",
    "image": "/games/preciojusto/catalog/031-lemon.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/31",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 79,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-32",
    "title": "Milk",
    "image": "/games/preciojusto/catalog/032-milk.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/32",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 349,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-33",
    "title": "Mulberry",
    "image": "/games/preciojusto/catalog/033-mulberry.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/33",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 499,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-34",
    "title": "Nescafe Coffee",
    "image": "/games/preciojusto/catalog/034-nescafe-coffee.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/34",
    "category": "ocio",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 799,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-35",
    "title": "Potatoes",
    "image": "/games/preciojusto/catalog/035-potatoes.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/35",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 229,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-36",
    "title": "Protein Powder",
    "image": "/games/preciojusto/catalog/036-protein-powder.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/36",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1999,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-37",
    "title": "Red Onions",
    "image": "/games/preciojusto/catalog/037-red-onions.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/37",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 199,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-38",
    "title": "Rice",
    "image": "/games/preciojusto/catalog/038-rice.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/38",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 599,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-39",
    "title": "Soft Drinks",
    "image": "/games/preciojusto/catalog/039-soft-drinks.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/39",
    "category": "ocio",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 199,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-40",
    "title": "Strawberry",
    "image": "/games/preciojusto/catalog/040-strawberry.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/40",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 399,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-41",
    "title": "Tissue Paper Box",
    "image": "/games/preciojusto/catalog/041-tissue-paper-box.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/41",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 249,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-42",
    "title": "Water",
    "image": "/games/preciojusto/catalog/042-water.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/42",
    "category": "baratos",
    "brandModel": null,
    "variant": "Alimentación · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 99,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-43",
    "title": "Decoration Swing",
    "image": "/games/preciojusto/catalog/043-decoration-swing.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/43",
    "category": "hogar",
    "brandModel": null,
    "variant": "Decoración · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 5999,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-44",
    "title": "Family Tree Photo Frame",
    "image": "/games/preciojusto/catalog/044-family-tree-photo-frame.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/44",
    "category": "hogar",
    "brandModel": null,
    "variant": "Decoración · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 2999,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-45",
    "title": "House Showpiece Plant",
    "image": "/games/preciojusto/catalog/045-house-showpiece-plant.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/45",
    "category": "hogar",
    "brandModel": null,
    "variant": "Decoración · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 3999,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-46",
    "title": "Plant Pot",
    "image": "/games/preciojusto/catalog/046-plant-pot.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/46",
    "category": "hogar",
    "brandModel": null,
    "variant": "Decoración · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1499,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-47",
    "title": "Table Lamp",
    "image": "/games/preciojusto/catalog/047-table-lamp.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/47",
    "category": "hogar",
    "brandModel": null,
    "variant": "Decoración · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 4999,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-48",
    "title": "Bamboo Spatula",
    "image": "/games/preciojusto/catalog/048-bamboo-spatula.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/48",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 799,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-49",
    "title": "Black Aluminium Cup",
    "image": "/games/preciojusto/catalog/049-black-aluminium-cup.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/49",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 599,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-50",
    "title": "Black Whisk",
    "image": "/games/preciojusto/catalog/050-black-whisk.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/50",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 999,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-51",
    "title": "Boxed Blender",
    "image": "/games/preciojusto/catalog/051-boxed-blender.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/51",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 3999,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-52",
    "title": "Carbon Steel Wok",
    "image": "/games/preciojusto/catalog/052-carbon-steel-wok.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/52",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 2999,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-53",
    "title": "Chopping Board",
    "image": "/games/preciojusto/catalog/053-chopping-board.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/53",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1299,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-54",
    "title": "Citrus Squeezer Yellow",
    "image": "/games/preciojusto/catalog/054-citrus-squeezer-yellow.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/54",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 899,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-55",
    "title": "Egg Slicer",
    "image": "/games/preciojusto/catalog/055-egg-slicer.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/55",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 699,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-56",
    "title": "Electric Stove",
    "image": "/games/preciojusto/catalog/056-electric-stove.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/56",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 4999,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-57",
    "title": "Fine Mesh Strainer",
    "image": "/games/preciojusto/catalog/057-fine-mesh-strainer.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/57",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 999,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-58",
    "title": "Fork",
    "image": "/games/preciojusto/catalog/058-fork.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/58",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 399,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-59",
    "title": "Glass",
    "image": "/games/preciojusto/catalog/059-glass.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/59",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 499,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-60",
    "title": "Grater Black",
    "image": "/games/preciojusto/catalog/060-grater-black.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/60",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1099,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-61",
    "title": "Hand Blender",
    "image": "/games/preciojusto/catalog/061-hand-blender.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/61",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 3499,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-62",
    "title": "Ice Cube Tray",
    "image": "/games/preciojusto/catalog/062-ice-cube-tray.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/62",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 599,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-63",
    "title": "Kitchen Sieve",
    "image": "/games/preciojusto/catalog/063-kitchen-sieve.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/63",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 799,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-64",
    "title": "Knife",
    "image": "/games/preciojusto/catalog/064-knife.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/64",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1499,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-65",
    "title": "Lunch Box",
    "image": "/games/preciojusto/catalog/065-lunch-box.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/65",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1299,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-66",
    "title": "Microwave Oven",
    "image": "/games/preciojusto/catalog/066-microwave-oven.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/66",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 8999,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-67",
    "title": "Mug Tree Stand",
    "image": "/games/preciojusto/catalog/067-mug-tree-stand.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/67",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1599,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-68",
    "title": "Pan",
    "image": "/games/preciojusto/catalog/068-pan.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/68",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 2499,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-69",
    "title": "Plate",
    "image": "/games/preciojusto/catalog/069-plate.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/69",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 399,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-70",
    "title": "Red Tongs",
    "image": "/games/preciojusto/catalog/070-red-tongs.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/70",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 699,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-71",
    "title": "Silver Pot With Glass Cap",
    "image": "/games/preciojusto/catalog/071-silver-pot-with-glass-cap.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/71",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 3999,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-72",
    "title": "Slotted Turner",
    "image": "/games/preciojusto/catalog/072-slotted-turner.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/72",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 899,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-73",
    "title": "Spice Rack",
    "image": "/games/preciojusto/catalog/073-spice-rack.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/73",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1999,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-74",
    "title": "Spoon",
    "image": "/games/preciojusto/catalog/074-spoon.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/74",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 499,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-75",
    "title": "Tray",
    "image": "/games/preciojusto/catalog/075-tray.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/75",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1699,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-76",
    "title": "Wooden Rolling Pin",
    "image": "/games/preciojusto/catalog/076-wooden-rolling-pin.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/76",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1199,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-77",
    "title": "Yellow Peeler",
    "image": "/games/preciojusto/catalog/077-yellow-peeler.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/77",
    "category": "hogar",
    "brandModel": null,
    "variant": "Accesorios de cocina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 599,
    "seller": "Referencia de catálogo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-78",
    "title": "Apple MacBook Pro 14 Inch Space Grey",
    "image": "/games/preciojusto/catalog/078-apple-macbook-pro-14-inch-space-grey.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/78",
    "category": "tecnologia",
    "brandModel": "Apple",
    "variant": "Apple · Ordenadores portátiles · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 199999,
    "seller": "Apple",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-79",
    "title": "Asus Zenbook Pro Dual Screen Laptop",
    "image": "/games/preciojusto/catalog/079-asus-zenbook-pro-dual-screen-laptop.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/79",
    "category": "tecnologia",
    "brandModel": "Asus",
    "variant": "Asus · Ordenadores portátiles · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 179999,
    "seller": "Asus",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-80",
    "title": "Huawei Matebook X Pro",
    "image": "/games/preciojusto/catalog/080-huawei-matebook-x-pro.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/80",
    "category": "tecnologia",
    "brandModel": "Huawei",
    "variant": "Huawei · Ordenadores portátiles · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 139999,
    "seller": "Huawei",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-81",
    "title": "Lenovo Yoga 920",
    "image": "/games/preciojusto/catalog/081-lenovo-yoga-920.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/81",
    "category": "tecnologia",
    "brandModel": "Lenovo",
    "variant": "Lenovo · Ordenadores portátiles · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 109999,
    "seller": "Lenovo",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-82",
    "title": "New DELL XPS 13 9300 Laptop",
    "image": "/games/preciojusto/catalog/082-new-dell-xps-13-9300-laptop.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/82",
    "category": "tecnologia",
    "brandModel": "Dell",
    "variant": "Dell · Ordenadores portátiles · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 149999,
    "seller": "Dell",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-83",
    "title": "Blue & Black Check Shirt",
    "image": "/games/preciojusto/catalog/083-blue-black-check-shirt.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/83",
    "category": "accesorios",
    "brandModel": "Fashion Trends",
    "variant": "Fashion Trends · Moda masculina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 2999,
    "seller": "Fashion Trends",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-84",
    "title": "Gigabyte Aorus Men Tshirt",
    "image": "/games/preciojusto/catalog/084-gigabyte-aorus-men-tshirt.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/84",
    "category": "accesorios",
    "brandModel": "Gigabyte",
    "variant": "Gigabyte · Moda masculina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 2499,
    "seller": "Gigabyte",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-85",
    "title": "Man Plaid Shirt",
    "image": "/games/preciojusto/catalog/085-man-plaid-shirt.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/85",
    "category": "accesorios",
    "brandModel": "Classic Wear",
    "variant": "Classic Wear · Moda masculina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 3499,
    "seller": "Classic Wear",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-86",
    "title": "Man Short Sleeve Shirt",
    "image": "/games/preciojusto/catalog/086-man-short-sleeve-shirt.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/86",
    "category": "accesorios",
    "brandModel": "Casual Comfort",
    "variant": "Casual Comfort · Moda masculina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1999,
    "seller": "Casual Comfort",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-87",
    "title": "Men Check Shirt",
    "image": "/games/preciojusto/catalog/087-men-check-shirt.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/87",
    "category": "accesorios",
    "brandModel": "Urban Chic",
    "variant": "Urban Chic · Moda masculina · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 2799,
    "seller": "Urban Chic",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-88",
    "title": "Nike Air Jordan 1 Red And Black",
    "image": "/games/preciojusto/catalog/088-nike-air-jordan-1-red-and-black.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/88",
    "category": "deporte",
    "brandModel": "Nike",
    "variant": "Nike · Calzado deportivo · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 14999,
    "seller": "Nike",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-89",
    "title": "Nike Baseball Cleats",
    "image": "/games/preciojusto/catalog/089-nike-baseball-cleats.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/89",
    "category": "deporte",
    "brandModel": "Nike",
    "variant": "Nike · Calzado deportivo · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 7999,
    "seller": "Nike",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-90",
    "title": "Puma Future Rider Trainers",
    "image": "/games/preciojusto/catalog/090-puma-future-rider-trainers.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/90",
    "category": "deporte",
    "brandModel": "Puma",
    "variant": "Puma · Calzado deportivo · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 8999,
    "seller": "Puma",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-91",
    "title": "Sports Sneakers Off White & Red",
    "image": "/games/preciojusto/catalog/091-sports-sneakers-off-white-red.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/91",
    "category": "deporte",
    "brandModel": "Off White",
    "variant": "Off White · Calzado deportivo · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 11999,
    "seller": "Off White",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-92",
    "title": "Sports Sneakers Off White Red",
    "image": "/games/preciojusto/catalog/092-sports-sneakers-off-white-red.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/92",
    "category": "deporte",
    "brandModel": "Off White",
    "variant": "Off White · Calzado deportivo · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 10999,
    "seller": "Off White",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-93",
    "title": "Brown Leather Belt Watch",
    "image": "/games/preciojusto/catalog/093-brown-leather-belt-watch.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/93",
    "category": "precio-medio",
    "brandModel": "Fashion Timepieces",
    "variant": "Fashion Timepieces · Relojería · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 8999,
    "seller": "Fashion Timepieces",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-94",
    "title": "Longines Master Collection",
    "image": "/games/preciojusto/catalog/094-longines-master-collection.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/94",
    "category": "precio-medio",
    "brandModel": "Longines",
    "variant": "Longines · Relojería · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 149999,
    "seller": "Longines",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-95",
    "title": "Rolex Cellini Date Black Dial",
    "image": "/games/preciojusto/catalog/095-rolex-cellini-date-black-dial.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/95",
    "category": "precio-medio",
    "brandModel": "Rolex",
    "variant": "Rolex · Relojería · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 899999,
    "seller": "Rolex",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-96",
    "title": "Rolex Cellini Moonphase",
    "image": "/games/preciojusto/catalog/096-rolex-cellini-moonphase.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/96",
    "category": "precio-medio",
    "brandModel": "Rolex",
    "variant": "Rolex · Relojería · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1299999,
    "seller": "Rolex",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-97",
    "title": "Rolex Datejust",
    "image": "/games/preciojusto/catalog/097-rolex-datejust.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/97",
    "category": "precio-medio",
    "brandModel": "Rolex",
    "variant": "Rolex · Relojería · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1099999,
    "seller": "Rolex",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-98",
    "title": "Rolex Submariner Watch",
    "image": "/games/preciojusto/catalog/098-rolex-submariner-watch.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/98",
    "category": "precio-medio",
    "brandModel": "Rolex",
    "variant": "Rolex · Relojería · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 1399999,
    "seller": "Rolex",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-99",
    "title": "Amazon Echo Plus",
    "image": "/games/preciojusto/catalog/099-amazon-echo-plus.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/99",
    "category": "tecnologia",
    "brandModel": "Amazon",
    "variant": "Amazon · Accesorios para móvil · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 9999,
    "seller": "Amazon",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  },
  {
    "id": "offline-100",
    "title": "Apple Airpods",
    "image": "/games/preciojusto/catalog/100-apple-airpods.webp",
    "asin": null,
    "detailPageUrl": "https://dummyjson.com/products/100",
    "category": "tecnologia",
    "brandModel": "Apple",
    "variant": "Apple · Accesorios para móvil · referencia offline",
    "marketplace": "Catálogo local",
    "currency": "EUR",
    "referencePriceCents": 12999,
    "seller": "Apple",
    "conditions": "Precio de referencia · catálogo offline · sin envío ni cupones",
    "source": "DummyJSON · catálogo público (https://dummyjson.com/products?limit=100&skip=0)",
    "capturedAt": "2026-08-22"
  }
] as const satisfies readonly PriceQuestion[];
