// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/crear/[game]" | "/dev/design" | "/juegos" | "/juegos/brisca" | "/juegos/chinchon" | "/juegos/cinquillo" | "/juegos/colores" | "/juegos/escala" | "/juegos/escoba" | "/juegos/laronda" | "/juegos/mayoria" | "/juegos/mus" | "/juegos/orden" | "/juegos/pocha" | "/juegos/sieteymedia" | "/juegos/tute" | "/mesa" | "/mesa/[code]" | "/reglas" | "/reglas/brisca" | "/reglas/cinquillo" | "/reglas/escoba" | "/reglas/mus" | "/reglas/pocha" | "/reglas/sieteymedia" | "/reglas/tute" | "/sala/[code]" | "/unirse" | "/unirse/[code]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/crear/[game]": { "game": string; }
  "/dev/design": {}
  "/juegos": {}
  "/juegos/brisca": {}
  "/juegos/chinchon": {}
  "/juegos/cinquillo": {}
  "/juegos/colores": {}
  "/juegos/escala": {}
  "/juegos/escoba": {}
  "/juegos/laronda": {}
  "/juegos/mayoria": {}
  "/juegos/mus": {}
  "/juegos/orden": {}
  "/juegos/pocha": {}
  "/juegos/sieteymedia": {}
  "/juegos/tute": {}
  "/mesa": {}
  "/mesa/[code]": { "code": string; }
  "/reglas": {}
  "/reglas/brisca": {}
  "/reglas/cinquillo": {}
  "/reglas/escoba": {}
  "/reglas/mus": {}
  "/reglas/pocha": {}
  "/reglas/sieteymedia": {}
  "/reglas/tute": {}
  "/sala/[code]": { "code": string; }
  "/unirse": {}
  "/unirse/[code]": { "code": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
