// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/crear/[game]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crear/[game]">> = Specific
  const handler = {} as typeof import("../../src/app/crear/[game]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dev/design/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/design">> = Specific
  const handler = {} as typeof import("../../src/app/dev/design/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/juegos/brisca/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/juegos/brisca">> = Specific
  const handler = {} as typeof import("../../src/app/juegos/brisca/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/juegos/chinchon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/juegos/chinchon">> = Specific
  const handler = {} as typeof import("../../src/app/juegos/chinchon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/juegos/cinquillo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/juegos/cinquillo">> = Specific
  const handler = {} as typeof import("../../src/app/juegos/cinquillo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/juegos/colores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/juegos/colores">> = Specific
  const handler = {} as typeof import("../../src/app/juegos/colores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/juegos/escala/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/juegos/escala">> = Specific
  const handler = {} as typeof import("../../src/app/juegos/escala/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/juegos/escoba/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/juegos/escoba">> = Specific
  const handler = {} as typeof import("../../src/app/juegos/escoba/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/juegos/laronda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/juegos/laronda">> = Specific
  const handler = {} as typeof import("../../src/app/juegos/laronda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/juegos/mayoria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/juegos/mayoria">> = Specific
  const handler = {} as typeof import("../../src/app/juegos/mayoria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/juegos/mus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/juegos/mus">> = Specific
  const handler = {} as typeof import("../../src/app/juegos/mus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/juegos/orden/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/juegos/orden">> = Specific
  const handler = {} as typeof import("../../src/app/juegos/orden/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/juegos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/juegos">> = Specific
  const handler = {} as typeof import("../../src/app/juegos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/juegos/pocha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/juegos/pocha">> = Specific
  const handler = {} as typeof import("../../src/app/juegos/pocha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/juegos/sieteymedia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/juegos/sieteymedia">> = Specific
  const handler = {} as typeof import("../../src/app/juegos/sieteymedia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/juegos/tute/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/juegos/tute">> = Specific
  const handler = {} as typeof import("../../src/app/juegos/tute/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mesa/[code]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mesa/[code]">> = Specific
  const handler = {} as typeof import("../../src/app/mesa/[code]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mesa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mesa">> = Specific
  const handler = {} as typeof import("../../src/app/mesa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reglas/brisca/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reglas/brisca">> = Specific
  const handler = {} as typeof import("../../src/app/reglas/brisca/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reglas/cinquillo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reglas/cinquillo">> = Specific
  const handler = {} as typeof import("../../src/app/reglas/cinquillo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reglas/escoba/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reglas/escoba">> = Specific
  const handler = {} as typeof import("../../src/app/reglas/escoba/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reglas/mus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reglas/mus">> = Specific
  const handler = {} as typeof import("../../src/app/reglas/mus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reglas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reglas">> = Specific
  const handler = {} as typeof import("../../src/app/reglas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reglas/pocha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reglas/pocha">> = Specific
  const handler = {} as typeof import("../../src/app/reglas/pocha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reglas/sieteymedia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reglas/sieteymedia">> = Specific
  const handler = {} as typeof import("../../src/app/reglas/sieteymedia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reglas/tute/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reglas/tute">> = Specific
  const handler = {} as typeof import("../../src/app/reglas/tute/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sala/[code]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sala/[code]">> = Specific
  const handler = {} as typeof import("../../src/app/sala/[code]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/unirse/[code]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unirse/[code]">> = Specific
  const handler = {} as typeof import("../../src/app/unirse/[code]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/unirse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unirse">> = Specific
  const handler = {} as typeof import("../../src/app/unirse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
