import type { ColorQuestion } from './content.ts';

type ColorQuestionSeed = Omit<ColorQuestion, 'category'>;

const LOGO_QUESTION_SEEDS: readonly ColorQuestionSeed[] = [
  { id: 'logo-google-g-inicial', prompt: 'En el logotipo de Google, ¿de qué color empieza la G mayúscula?', allowMultiple: false, correctColors: ['azul'] },
  { id: 'logo-google-primer-o', prompt: 'En el logotipo de Google, ¿de qué color es la primera letra o?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-google-segundo-o', prompt: 'En el logotipo de Google, ¿de qué color es la segunda letra o?', allowMultiple: false, correctColors: ['amarillo'] },
  { id: 'logo-google-g-minuscula', prompt: 'En el logotipo de Google, ¿de qué color es la g minúscula?', allowMultiple: false, correctColors: ['azul'] },
  { id: 'logo-google-l', prompt: 'En el logotipo de Google, ¿de qué color es la letra l?', allowMultiple: false, correctColors: ['verde'] },
  { id: 'logo-google-e', prompt: 'En el logotipo de Google, ¿de qué color es la letra e final?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-microsoft-cuadro-superior-izquierdo', prompt: '¿De qué color es el cuadro superior izquierdo del símbolo de Microsoft?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-microsoft-cuadro-superior-derecho', prompt: '¿De qué color es el cuadro superior derecho del símbolo de Microsoft?', allowMultiple: false, correctColors: ['verde'] },
  { id: 'logo-microsoft-cuadro-inferior-izquierdo', prompt: '¿De qué color es el cuadro inferior izquierdo del símbolo de Microsoft?', allowMultiple: false, correctColors: ['azul'] },
  { id: 'logo-microsoft-cuadro-inferior-derecho', prompt: '¿De qué color es el cuadro inferior derecho del símbolo de Microsoft?', allowMultiple: false, correctColors: ['amarillo'] },
  { id: 'logo-chrome-centro', prompt: '¿De qué color es el círculo central del icono de Google Chrome?', allowMultiple: false, correctColors: ['azul'] },
  { id: 'logo-gmail-m', prompt: '¿De qué color es la M que forma el contorno principal del icono actual de Gmail?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-drive-sector-inferior-derecho', prompt: '¿De qué color es el sector inferior derecho del triángulo de Google Drive?', allowMultiple: false, correctColors: ['azul'] },
  { id: 'logo-maps-punto-central', prompt: '¿De qué color es el punto central del pin de Google Maps?', allowMultiple: false, correctColors: ['azul'] },
  { id: 'logo-calendar-numero', prompt: '¿De qué color son las cifras «31» del icono de Google Calendar?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-photos-petalo-superior', prompt: '¿De qué color es el pétalo superior del molinillo de Google Fotos?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-apple-monocromo', prompt: '¿De qué color es la manzana en la versión monocroma clásica del logotipo de Apple sobre fondo blanco?', allowMultiple: false, correctColors: ['negro'] },
  { id: 'logo-android-mascota', prompt: '¿De qué color se representa tradicionalmente la mascota robot de Android?', allowMultiple: false, correctColors: ['verde'] },
  { id: 'logo-github-octocat', prompt: '¿De qué color aparece el Octocat en el icono clásico de GitHub sobre fondo blanco?', allowMultiple: false, correctColors: ['negro'] },
  { id: 'logo-gitlab-rombo-central', prompt: '¿Qué color domina en el rombo central de la cabeza de zorro del logotipo de GitLab?', allowMultiple: false, correctColors: ['naranja'] },
  { id: 'logo-stack-overflow-rayas', prompt: '¿De qué color son las líneas que salen de la bandeja en el logotipo de Stack Overflow?', allowMultiple: false, correctColors: ['naranja'] },
  { id: 'logo-dropbox-rombos', prompt: '¿De qué color son los rombos de la versión clásica del logotipo de Dropbox?', allowMultiple: false, correctColors: ['azul'] },
  { id: 'logo-linkedin-letras-icono', prompt: '¿De qué color son las letras «in» dentro del icono azul de LinkedIn?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-reddit-alien', prompt: '¿De qué color es la cabeza del alienígena dentro del icono naranja de Reddit?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-pinterest-p', prompt: '¿De qué color es la P dentro del círculo rojo del icono de Pinterest?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-twitch-marca', prompt: '¿De qué color es la marca denominativa clásica de Twitch sobre fondo blanco?', allowMultiple: false, correctColors: ['morado'] },
  { id: 'logo-discord-mascota', prompt: '¿De qué color aparece Clyde, la mascota, dentro del icono morado de Discord?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-whatsapp-telefono', prompt: '¿De qué color es el auricular dentro del icono verde de WhatsApp?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-telegram-avion', prompt: '¿De qué color es el avión de papel dentro del icono azul de Telegram?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-instagram-camara', prompt: '¿De qué color es el trazo de cámara en la versión habitual del icono degradado de Instagram?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-facebook-f', prompt: '¿De qué color es la letra f dentro del icono azul de Facebook?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-x-trazo', prompt: '¿De qué color es la X en la versión del icono de X con fondo negro?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-threads-trazo', prompt: '¿De qué color es el símbolo @ estilizado en el icono de Threads con fondo negro?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-tiktok-nota-principal', prompt: '¿De qué color es el trazo principal de la nota del icono de TikTok sobre fondo negro?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-netflix-n', prompt: '¿De qué color es la N del icono de Netflix sobre fondo negro?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-prime-video-sonrisa', prompt: '¿De qué color es la flecha con forma de sonrisa del logotipo de Prime Video sobre fondo blanco?', allowMultiple: false, correctColors: ['azul'] },
  { id: 'logo-disney-plus-arco', prompt: '¿De qué color es el arco que pasa sobre la palabra Disney en la versión clara del logotipo de Disney+?', allowMultiple: false, correctColors: ['azul'] },
  { id: 'logo-hbo-letras', prompt: '¿De qué color son las letras del logotipo clásico de HBO sobre fondo blanco?', allowMultiple: false, correctColors: ['negro'] },
  { id: 'logo-paramount-montana', prompt: '¿De qué color es la montaña dentro del círculo azul del logotipo clásico de Paramount?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-pixar-lampara', prompt: '¿De qué color metálico se representa normalmente la lámpara Luxo Jr. en el logotipo de Pixar?', allowMultiple: false, correctColors: ['gris'] },
  { id: 'logo-dreamworks-luna', prompt: '¿De qué color aparece la luna en la versión clásica del logotipo de DreamWorks sobre cielo azul?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-nickelodeon-letras', prompt: '¿De qué color es la marca denominativa actual de Nickelodeon sobre fondo blanco?', allowMultiple: false, correctColors: ['naranja'] },
  { id: 'logo-cartoon-network-fondo-c', prompt: '¿De qué color es el cuadro situado detrás de la C en el logotipo ajedrezado clásico de Cartoon Network?', allowMultiple: false, correctColors: ['negro'] },
  { id: 'logo-bbc-cajas', prompt: '¿De qué color son las tres cajas que contienen las letras del logotipo clásico de la BBC?', allowMultiple: false, correctColors: ['negro'] },
  { id: 'logo-cnn-letras', prompt: '¿De qué color es habitualmente el trazo continuo del logotipo de CNN?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-espn-letras', prompt: '¿De qué color se presenta habitualmente el logotipo de ESPN sobre fondo blanco?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-national-geographic-marco', prompt: '¿De qué color es el marco rectangular del logotipo de National Geographic?', allowMultiple: false, correctColors: ['amarillo'] },
  { id: 'logo-discovery-globo', prompt: '¿Qué color domina en el globo terráqueo del logotipo clásico de Discovery Channel?', allowMultiple: false, correctColors: ['azul'] },
  { id: 'logo-history-h', prompt: '¿Qué color domina en la gran H metálica del logotipo clásico de History Channel?', allowMultiple: false, correctColors: ['amarillo'] },
  { id: 'logo-airbnb-belo', prompt: '¿De qué color se presenta el símbolo Bélo de Airbnb en su versión corporativa sobre fondo blanco?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-tripadvisor-ojo-izquierdo', prompt: 'Mirando de frente el búho de Tripadvisor, ¿de qué color es el aro exterior de su ojo izquierdo?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-booking-marca', prompt: '¿De qué color se presenta habitualmente la marca Booking.com sobre fondo blanco?', allowMultiple: false, correctColors: ['azul'] },
  { id: 'logo-uber-marca', prompt: '¿De qué color es la marca denominativa de Uber en su versión principal sobre fondo blanco?', allowMultiple: false, correctColors: ['negro'] },
  { id: 'logo-lyft-marca', prompt: '¿De qué color se presenta tradicionalmente la marca denominativa de Lyft?', allowMultiple: false, correctColors: ['rosa'] },
  { id: 'logo-tesla-t', prompt: '¿De qué color se presenta habitualmente la T del logotipo de Tesla sobre fondo blanco?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-audi-aros-planos', prompt: '¿De qué color son los cuatro aros en la versión plana monocroma de Audi sobre fondo blanco?', allowMultiple: false, correctColors: ['negro'] },
  { id: 'logo-mercedes-estrella-metal', prompt: '¿Qué color tiene el acabado metálico clásico de la estrella de Mercedes-Benz?', allowMultiple: false, correctColors: ['gris'] },
  { id: 'logo-bmw-cuadrante-superior-derecho', prompt: '¿De qué color es el cuadrante superior derecho del círculo interior del logotipo de BMW?', allowMultiple: false, correctColors: ['azul'] },
  { id: 'logo-toyota-elipses-rojas', prompt: '¿De qué color son las tres elipses de la versión corporativa roja del símbolo de Toyota?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-volkswagen-v', prompt: '¿De qué color es la V dentro del emblema circular azul clásico de Volkswagen?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-peugeot-leon', prompt: '¿De qué color es la cabeza de león dentro del escudo negro actual de Peugeot?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-renault-rombo', prompt: '¿De qué color es el rombo en la versión plana actual del logotipo de Renault sobre fondo blanco?', allowMultiple: false, correctColors: ['negro'] },
  { id: 'logo-shell-interior', prompt: '¿De qué color es el interior de la concha del logotipo de Shell?', allowMultiple: false, correctColors: ['amarillo'] },
  { id: 'logo-bp-petalos-exteriores', prompt: '¿De qué color son los pétalos exteriores del símbolo Helios de BP?', allowMultiple: false, correctColors: ['verde'] },
  { id: 'logo-mcdonalds-arcos', prompt: '¿De qué color son los arcos del logotipo clásico de McDonald’s?', allowMultiple: false, correctColors: ['amarillo'] },
  { id: 'logo-burger-king-letras', prompt: '¿De qué color son las palabras Burger King dentro del pan del logotipo?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-starbucks-sirena', prompt: '¿De qué color es la sirena dentro del círculo verde del logotipo de Starbucks?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-pepsi-zona-superior', prompt: '¿De qué color es la zona superior del globo del logotipo de Pepsi?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-cocacola-letras', prompt: '¿De qué color es la caligrafía de Coca-Cola dentro de su disco rojo clásico?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-fanta-hoja', prompt: '¿De qué color es la hoja situada sobre la palabra Fanta en su logotipo clásico?', allowMultiple: false, correctColors: ['verde'] },
  { id: 'logo-pringles-bigote', prompt: '¿De qué color es el bigote de Mr. P, la mascota de Pringles?', allowMultiple: false, correctColors: ['negro'] },
  { id: 'logo-kelloggs-marca', prompt: '¿De qué color se presenta tradicionalmente la firma del logotipo de Kellogg’s?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-nutella-n', prompt: '¿De qué color es la letra n inicial del logotipo de Nutella?', allowMultiple: false, correctColors: ['negro'] },
  { id: 'logo-lego-letras', prompt: '¿De qué color es el relleno de las letras LEGO dentro del cuadrado rojo?', allowMultiple: false, correctColors: ['blanco'] },
  { id: 'logo-playmobil-marca', prompt: '¿De qué color es la palabra Playmobil en su logotipo clásico?', allowMultiple: false, correctColors: ['azul'] },
  { id: 'logo-ikea-letras', prompt: '¿De qué color son las letras IKEA dentro del óvalo amarillo?', allowMultiple: false, correctColors: ['azul'] },
  { id: 'logo-adidas-tres-barras', prompt: '¿De qué color son las tres barras en la versión monocroma principal de Adidas sobre fondo blanco?', allowMultiple: false, correctColors: ['negro'] },
  { id: 'logo-puma-felino', prompt: '¿De qué color es el felino en la versión monocroma clásica de Puma sobre fondo blanco?', allowMultiple: false, correctColors: ['negro'] },
  { id: 'logo-new-balance-n', prompt: '¿De qué color se presenta tradicionalmente la N con líneas de velocidad de New Balance?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-lacoste-cocodrilo', prompt: '¿Qué color domina en el cuerpo del cocodrilo del logotipo clásico de Lacoste?', allowMultiple: false, correctColors: ['verde'] },
  { id: 'logo-rolex-corona', prompt: '¿De qué color es la corona de cinco puntas del logotipo de Rolex?', allowMultiple: false, correctColors: ['amarillo'] },
  { id: 'logo-mitsubishi-rombos', prompt: '¿De qué color son los tres rombos del logotipo principal de Mitsubishi?', allowMultiple: false, correctColors: ['rojo'] },
  { id: 'logo-skoda-flecha', prompt: '¿De qué color se representa tradicionalmente la flecha alada del logotipo de Škoda?', allowMultiple: false, correctColors: ['verde'] },
];

export const LOGO_COLOR_QUESTIONS: readonly ColorQuestion[] = LOGO_QUESTION_SEEDS.map(
  (question) => ({ ...question, category: 'logos' }),
);
