import type { ColorQuestion } from './content.ts';

/**
 * Preguntas propias de respuesta múltiple. Se centran en combinaciones
 * reconocibles y estables; el texto concreta la versión cuando un diseño ha
 * cambiado con los años. Todas caben en las cuatro fichas que admite la UI.
 */
export const MULTI_COLOR_QUESTIONS: readonly ColorQuestion[] = [
  // Animación
  { id: 'multi-simpsons-homer-ropa', prompt: '¿De qué colores son la camisa y los pantalones habituales de Homer Simpson?', category: 'animacion', allowMultiple: true, correctColors: ['blanco', 'azul'] },
  { id: 'multi-simpsons-marge-vestido-pelo', prompt: '¿De qué colores son el vestido y el pelo de Marge Simpson?', category: 'animacion', allowMultiple: true, correctColors: ['verde', 'azul'] },
  { id: 'multi-simpsons-bart-ropa', prompt: '¿De qué colores son la camiseta y los pantalones cortos habituales de Bart Simpson?', category: 'animacion', allowMultiple: true, correctColors: ['naranja', 'azul'] },
  { id: 'multi-simpsons-lisa-ropa-collar', prompt: '¿De qué colores son el vestido y el collar de Lisa Simpson?', category: 'animacion', allowMultiple: true, correctColors: ['rojo', 'blanco'] },
  { id: 'multi-mario-ropa-clasica', prompt: '¿Qué dos colores dominan en la gorra y el peto clásicos de Mario?', category: 'animacion', allowMultiple: true, correctColors: ['rojo', 'azul'] },
  { id: 'multi-luigi-ropa-clasica', prompt: '¿Qué dos colores dominan en la gorra y el peto clásicos de Luigi?', category: 'animacion', allowMultiple: true, correctColors: ['verde', 'azul'] },
  { id: 'multi-mickey-pantalon-zapatos', prompt: '¿De qué colores son los pantalones cortos y los zapatos clásicos de Mickey Mouse?', category: 'animacion', allowMultiple: true, correctColors: ['rojo', 'amarillo'] },
  { id: 'multi-donald-chaqueta-pajarita', prompt: '¿De qué colores son la chaqueta marinera y la pajarita del Pato Donald?', category: 'animacion', allowMultiple: true, correctColors: ['azul', 'rojo'] },
  { id: 'multi-winnie-pooh-cuerpo-camiseta', prompt: '¿De qué colores son el cuerpo y la camiseta de Winnie the Pooh?', category: 'animacion', allowMultiple: true, correctColors: ['amarillo', 'rojo'] },
  { id: 'multi-pokeball-clasica', prompt: '¿Qué tres colores tiene una Poké Ball clásica?', category: 'animacion', allowMultiple: true, correctColors: ['rojo', 'blanco', 'negro'] },
  { id: 'multi-pikachu-cuerpo-orejas-mejillas', prompt: '¿Qué colores tienen el cuerpo, las puntas de las orejas y las mejillas de Pikachu?', category: 'animacion', allowMultiple: true, correctColors: ['amarillo', 'negro', 'rojo'] },
  { id: 'multi-nemo-cuerpo-rayas', prompt: '¿Qué tres colores forman el cuerpo y las rayas de Nemo?', category: 'animacion', allowMultiple: true, correctColors: ['naranja', 'blanco', 'negro'] },
  { id: 'multi-buzz-traje', prompt: '¿Qué tres colores dominan en el traje espacial de Buzz Lightyear?', category: 'animacion', allowMultiple: true, correctColors: ['blanco', 'verde', 'morado'] },
  { id: 'multi-sulley-pelo-manchas', prompt: '¿De qué colores son el pelo y las manchas de Sulley en Monstruos, S. A.?', category: 'animacion', allowMultiple: true, correctColors: ['azul', 'morado'] },
  { id: 'multi-mr-increible-traje', prompt: '¿Qué tres colores dominan en el traje de Mr. Increíble?', category: 'animacion', allowMultiple: true, correctColors: ['rojo', 'negro', 'amarillo'] },

  // Series
  { id: 'multi-friends-puntos-logo', prompt: '¿Qué tres colores tienen los puntos del logotipo de Friends?', category: 'series', allowMultiple: true, correctColors: ['rojo', 'amarillo', 'azul'] },
  { id: 'multi-stranger-things-logo', prompt: '¿Qué dos colores dominan en el logotipo clásico de Stranger Things?', category: 'series', allowMultiple: true, correctColors: ['rojo', 'negro'] },
  { id: 'multi-squid-game-guardias', prompt: '¿De qué colores son el uniforme y la máscara de los guardias de El juego del calamar?', category: 'series', allowMultiple: true, correctColors: ['rosa', 'negro'] },
  { id: 'multi-doctor-who-tardis', prompt: '¿Qué dos colores dominan en el exterior de la TARDIS de Doctor Who?', category: 'series', allowMultiple: true, correctColors: ['azul', 'blanco'] },
  { id: 'multi-star-trek-mando', prompt: '¿Qué colores dominan en el uniforme de mando clásico de Star Trek y su cuello?', category: 'series', allowMultiple: true, correctColors: ['amarillo', 'negro'] },
  { id: 'multi-breaking-bad-logo', prompt: '¿Qué dos colores dominan en el logotipo habitual de Breaking Bad?', category: 'series', allowMultiple: true, correctColors: ['verde', 'blanco'] },

  // Cine
  { id: 'multi-superman-traje-clasico', prompt: '¿Qué tres colores dominan en el traje clásico de Superman?', category: 'cine', allowMultiple: true, correctColors: ['azul', 'rojo', 'amarillo'] },
  { id: 'multi-batman-emblema-1989', prompt: '¿De qué colores es el emblema del pecho de Batman en la película de 1989?', category: 'cine', allowMultiple: true, correctColors: ['negro', 'amarillo'] },
  { id: 'multi-kill-bill-chandal', prompt: '¿De qué colores es el chándal de la Novia en Kill Bill?', category: 'cine', allowMultiple: true, correctColors: ['amarillo', 'negro'] },
  { id: 'multi-matrix-codigo', prompt: '¿De qué colores son el código y el fondo en la imagen clásica de Matrix?', category: 'cine', allowMultiple: true, correctColors: ['verde', 'negro'] },
  { id: 'multi-cazafantasmas-simbolo', prompt: '¿Qué tres colores tiene el símbolo clásico de Los Cazafantasmas?', category: 'cine', allowMultiple: true, correctColors: ['rojo', 'blanco', 'negro'] },
  { id: 'multi-minions-cuerpo-peto', prompt: '¿De qué colores son el cuerpo y el peto de los Minions?', category: 'cine', allowMultiple: true, correctColors: ['amarillo', 'azul'] },
  { id: 'multi-darth-vader-sable', prompt: '¿De qué colores son la armadura de Darth Vader y su sable de luz?', category: 'cine', allowMultiple: true, correctColors: ['negro', 'rojo'] },
  { id: 'multi-gryffindor-colores', prompt: '¿Qué dos colores identifican tradicionalmente a Gryffindor en Harry Potter?', category: 'cine', allowMultiple: true, correctColors: ['rojo', 'amarillo'] },
  { id: 'multi-regreso-futuro-logo', prompt: '¿Qué tres colores dominan en el rótulo clásico de Regreso al futuro?', category: 'cine', allowMultiple: true, correctColors: ['amarillo', 'naranja', 'azul'] },
  { id: 'multi-dorothy-vestido-zapatos', prompt: '¿De qué colores son el vestido y los zapatos de Dorothy en El mago de Oz?', category: 'cine', allowMultiple: true, correctColors: ['azul', 'rojo'] },

  // Banderas: se preguntan los colores principales, sin desglosar matices heráldicos.
  { id: 'multi-bandera-alemania', prompt: '¿Qué tres colores tiene la bandera de Alemania?', category: 'banderas', allowMultiple: true, correctColors: ['negro', 'rojo', 'amarillo'] },
  { id: 'multi-bandera-francia', prompt: '¿Qué tres colores tiene la bandera de Francia?', category: 'banderas', allowMultiple: true, correctColors: ['azul', 'blanco', 'rojo'] },
  { id: 'multi-bandera-italia', prompt: '¿Qué tres colores tiene la bandera de Italia?', category: 'banderas', allowMultiple: true, correctColors: ['verde', 'blanco', 'rojo'] },
  { id: 'multi-bandera-belgica', prompt: '¿Qué tres colores tiene la bandera de Bélgica?', category: 'banderas', allowMultiple: true, correctColors: ['negro', 'amarillo', 'rojo'] },
  { id: 'multi-bandera-irlanda', prompt: '¿Qué tres colores tiene la bandera de Irlanda?', category: 'banderas', allowMultiple: true, correctColors: ['verde', 'blanco', 'naranja'] },
  { id: 'multi-bandera-ucrania', prompt: '¿Qué dos colores tiene la bandera de Ucrania?', category: 'banderas', allowMultiple: true, correctColors: ['azul', 'amarillo'] },
  { id: 'multi-bandera-polonia', prompt: '¿Qué dos colores tiene la bandera de Polonia?', category: 'banderas', allowMultiple: true, correctColors: ['blanco', 'rojo'] },
  { id: 'multi-bandera-espana', prompt: '¿Qué dos colores forman las franjas de la bandera de España?', category: 'banderas', allowMultiple: true, correctColors: ['rojo', 'amarillo'] },
  { id: 'multi-bandera-paises-bajos', prompt: '¿Qué tres colores tiene la bandera de los Países Bajos?', category: 'banderas', allowMultiple: true, correctColors: ['rojo', 'blanco', 'azul'] },
  { id: 'multi-bandera-rumania', prompt: '¿Qué tres colores tiene la bandera de Rumanía?', category: 'banderas', allowMultiple: true, correctColors: ['azul', 'amarillo', 'rojo'] },
  { id: 'multi-bandera-bulgaria', prompt: '¿Qué tres colores tiene la bandera de Bulgaria?', category: 'banderas', allowMultiple: true, correctColors: ['blanco', 'verde', 'rojo'] },
  { id: 'multi-bandera-hungria', prompt: '¿Qué tres colores tiene la bandera de Hungría?', category: 'banderas', allowMultiple: true, correctColors: ['rojo', 'blanco', 'verde'] },
  { id: 'multi-bandera-austria', prompt: '¿Qué dos colores tiene la bandera de Austria?', category: 'banderas', allowMultiple: true, correctColors: ['rojo', 'blanco'] },
  { id: 'multi-bandera-japon', prompt: '¿Qué dos colores tiene la bandera de Japón?', category: 'banderas', allowMultiple: true, correctColors: ['blanco', 'rojo'] },
  { id: 'multi-bandera-suiza', prompt: '¿Qué dos colores tiene la bandera de Suiza?', category: 'banderas', allowMultiple: true, correctColors: ['rojo', 'blanco'] },
  { id: 'multi-bandera-suecia', prompt: '¿Qué dos colores tiene la bandera de Suecia?', category: 'banderas', allowMultiple: true, correctColors: ['azul', 'amarillo'] },
  { id: 'multi-bandera-dinamarca', prompt: '¿Qué dos colores tiene la bandera de Dinamarca?', category: 'banderas', allowMultiple: true, correctColors: ['rojo', 'blanco'] },
  { id: 'multi-bandera-finlandia', prompt: '¿Qué dos colores tiene la bandera de Finlandia?', category: 'banderas', allowMultiple: true, correctColors: ['blanco', 'azul'] },
  { id: 'multi-bandera-grecia', prompt: '¿Qué dos colores tiene la bandera de Grecia?', category: 'banderas', allowMultiple: true, correctColors: ['azul', 'blanco'] },
  { id: 'multi-bandera-canada', prompt: '¿Qué dos colores tiene la bandera de Canadá?', category: 'banderas', allowMultiple: true, correctColors: ['rojo', 'blanco'] },
  { id: 'multi-bandera-brasil', prompt: '¿Qué cuatro colores principales tiene la bandera de Brasil?', category: 'banderas', allowMultiple: true, correctColors: ['verde', 'amarillo', 'azul', 'blanco'] },
  { id: 'multi-bandera-india', prompt: '¿Qué cuatro colores tiene la bandera de India, incluido el chakra?', category: 'banderas', allowMultiple: true, correctColors: ['naranja', 'blanco', 'verde', 'azul'] },
  { id: 'multi-bandera-estonia', prompt: '¿Qué tres colores tiene la bandera de Estonia?', category: 'banderas', allowMultiple: true, correctColors: ['azul', 'negro', 'blanco'] },
  { id: 'multi-bandera-lituania', prompt: '¿Qué tres colores tiene la bandera de Lituania?', category: 'banderas', allowMultiple: true, correctColors: ['amarillo', 'verde', 'rojo'] },
  { id: 'multi-bandera-colombia', prompt: '¿Qué tres colores tiene la bandera de Colombia?', category: 'banderas', allowMultiple: true, correctColors: ['amarillo', 'azul', 'rojo'] },
  { id: 'multi-bandera-mexico', prompt: '¿Qué tres colores forman las franjas de la bandera de México?', category: 'banderas', allowMultiple: true, correctColors: ['verde', 'blanco', 'rojo'] },
  { id: 'multi-bandera-argentina', prompt: '¿Qué tres colores aparecen en la bandera de Argentina, incluido el sol?', category: 'banderas', allowMultiple: true, correctColors: ['azul', 'blanco', 'amarillo'] },
  { id: 'multi-bandera-estados-unidos', prompt: '¿Qué tres colores tiene la bandera de Estados Unidos?', category: 'banderas', allowMultiple: true, correctColors: ['rojo', 'blanco', 'azul'] },
  { id: 'multi-bandera-republica-checa', prompt: '¿Qué tres colores tiene la bandera de la República Checa?', category: 'banderas', allowMultiple: true, correctColors: ['blanco', 'rojo', 'azul'] },
  { id: 'multi-bandera-islandia', prompt: '¿Qué tres colores tiene la bandera de Islandia?', category: 'banderas', allowMultiple: true, correctColors: ['azul', 'blanco', 'rojo'] },
  { id: 'multi-bandera-noruega', prompt: '¿Qué tres colores tiene la bandera de Noruega?', category: 'banderas', allowMultiple: true, correctColors: ['rojo', 'blanco', 'azul'] },
  { id: 'multi-bandera-rusia', prompt: '¿Qué tres colores tiene la bandera de Rusia?', category: 'banderas', allowMultiple: true, correctColors: ['blanco', 'azul', 'rojo'] },

  // Logos y marcas
  { id: 'multi-logo-google', prompt: '¿Qué cuatro colores tienen las letras del logotipo de Google?', category: 'logos', allowMultiple: true, correctColors: ['azul', 'rojo', 'amarillo', 'verde'] },
  { id: 'multi-logo-microsoft', prompt: '¿Qué cuatro colores tienen los cuadrados del logotipo de Microsoft?', category: 'logos', allowMultiple: true, correctColors: ['rojo', 'verde', 'azul', 'amarillo'] },
  { id: 'multi-logo-mastercard', prompt: '¿Qué dos colores tienen los círculos del logotipo de Mastercard?', category: 'logos', allowMultiple: true, correctColors: ['rojo', 'naranja'] },
  { id: 'multi-logo-pepsi', prompt: '¿Qué tres colores tiene el círculo del logotipo de Pepsi?', category: 'logos', allowMultiple: true, correctColors: ['rojo', 'blanco', 'azul'] },
  { id: 'multi-logo-ikea', prompt: '¿Qué dos colores tiene el logotipo clásico de IKEA?', category: 'logos', allowMultiple: true, correctColors: ['azul', 'amarillo'] },
  { id: 'multi-logo-mcdonalds', prompt: '¿Qué dos colores dominan en el logotipo clásico de McDonald’s?', category: 'logos', allowMultiple: true, correctColors: ['rojo', 'amarillo'] },
  { id: 'multi-logo-fedex', prompt: '¿De qué colores son «Fed» y «Ex» en la versión principal del logotipo de FedEx?', category: 'logos', allowMultiple: true, correctColors: ['morado', 'naranja'] },
  { id: 'multi-logo-youtube', prompt: '¿Qué dos colores tiene el icono principal de YouTube?', category: 'logos', allowMultiple: true, correctColors: ['rojo', 'blanco'] },
  { id: 'multi-logo-spotify', prompt: '¿Qué dos colores tiene el icono habitual de Spotify?', category: 'logos', allowMultiple: true, correctColors: ['verde', 'negro'] },
  { id: 'multi-logo-slack', prompt: '¿Qué cuatro colores tiene el símbolo multicolor de Slack?', category: 'logos', allowMultiple: true, correctColors: ['rojo', 'amarillo', 'verde', 'azul'] },
  { id: 'multi-logo-ebay', prompt: '¿Qué cuatro colores tienen las letras del logotipo de eBay?', category: 'logos', allowMultiple: true, correctColors: ['rojo', 'azul', 'amarillo', 'verde'] },
  { id: 'multi-logo-lego', prompt: '¿Qué cuatro colores tiene el logotipo clásico de LEGO?', category: 'logos', allowMultiple: true, correctColors: ['rojo', 'amarillo', 'blanco', 'negro'] },
  { id: 'multi-logo-bmw', prompt: '¿Qué tres colores aparecen en el emblema clásico de BMW?', category: 'logos', allowMultiple: true, correctColors: ['azul', 'blanco', 'negro'] },
  { id: 'multi-logo-dominos', prompt: '¿Qué tres colores tiene la ficha del logotipo de Domino’s?', category: 'logos', allowMultiple: true, correctColors: ['rojo', 'azul', 'blanco'] },
  { id: 'multi-logo-nasa-meatball', prompt: '¿Qué tres colores dominan en el logotipo «meatball» de la NASA?', category: 'logos', allowMultiple: true, correctColors: ['azul', 'rojo', 'blanco'] },
  { id: 'multi-logo-instagram', prompt: '¿Qué cuatro colores dominan en el degradado del icono de Instagram?', category: 'logos', allowMultiple: true, correctColors: ['morado', 'rosa', 'naranja', 'amarillo'] },
  { id: 'multi-logo-playstation-original', prompt: '¿Qué cuatro colores tiene la P con la S del logotipo original de PlayStation?', category: 'logos', allowMultiple: true, correctColors: ['rojo', 'amarillo', 'verde', 'azul'] },

  // Juegos y videojuegos
  { id: 'multi-juego-botones-playstation', prompt: '¿Qué cuatro colores tienen los símbolos clásicos del mando de PlayStation?', category: 'juegos', allowMultiple: true, correctColors: ['verde', 'rojo', 'azul', 'rosa'] },
  { id: 'multi-juego-xbox-icono', prompt: '¿Qué dos colores tiene tradicionalmente el icono de Xbox?', category: 'juegos', allowMultiple: true, correctColors: ['verde', 'blanco'] },
  { id: 'multi-juego-nintendo-switch', prompt: '¿Qué dos colores tiene la versión más conocida del logotipo de Nintendo Switch?', category: 'juegos', allowMultiple: true, correctColors: ['rojo', 'blanco'] },
  { id: 'multi-juego-portales', prompt: '¿De qué colores son los dos portales del videojuego Portal?', category: 'juegos', allowMultiple: true, correctColors: ['azul', 'naranja'] },
  { id: 'multi-juego-minecraft-bloque-hierba', prompt: '¿Qué dos colores dominan en un bloque de hierba de Minecraft?', category: 'juegos', allowMultiple: true, correctColors: ['verde', 'marrón'] },
  { id: 'multi-juego-pokemon-logo', prompt: '¿Qué dos colores dominan en el logotipo internacional clásico de Pokémon?', category: 'juegos', allowMultiple: true, correctColors: ['amarillo', 'azul'] },
  { id: 'multi-juego-seta-mario', prompt: '¿Qué dos colores tiene la seta potenciadora clásica de Super Mario?', category: 'juegos', allowMultiple: true, correctColors: ['rojo', 'blanco'] },
  { id: 'multi-juego-pacman-laberinto', prompt: '¿De qué colores son Pac-Man y las paredes del laberinto clásico?', category: 'juegos', allowMultiple: true, correctColors: ['amarillo', 'azul'] },
  { id: 'multi-juego-master-ball', prompt: '¿Qué cuatro colores tiene una Master Ball?', category: 'juegos', allowMultiple: true, correctColors: ['morado', 'blanco', 'rosa', 'negro'] },
  { id: 'multi-juego-sonic-zapatillas', prompt: '¿Qué tres colores dominan en Sonic y sus zapatillas?', category: 'juegos', allowMultiple: true, correctColors: ['azul', 'rojo', 'blanco'] },
  { id: 'multi-juego-tails-zapatillas', prompt: '¿Qué tres colores dominan en Tails y sus zapatillas?', category: 'juegos', allowMultiple: true, correctColors: ['naranja', 'rojo', 'blanco'] },
  { id: 'multi-juego-knuckles-zapatillas', prompt: '¿Qué tres colores dominan en Knuckles y sus zapatillas?', category: 'juegos', allowMultiple: true, correctColors: ['rojo', 'verde', 'amarillo'] },

  // Cultura general y objetos cotidianos
  { id: 'multi-cultura-semaforo', prompt: '¿Qué tres colores tiene un semáforo de tráfico?', category: 'cultura', allowMultiple: true, correctColors: ['rojo', 'amarillo', 'verde'] },
  { id: 'multi-cultura-ajedrez', prompt: '¿Qué dos colores tienen tradicionalmente las piezas de ajedrez?', category: 'cultura', allowMultiple: true, correctColors: ['blanco', 'negro'] },
  { id: 'multi-cultura-piano', prompt: '¿Qué dos colores tienen las teclas de un piano?', category: 'cultura', allowMultiple: true, correctColors: ['blanco', 'negro'] },
  { id: 'multi-cultura-union-europea', prompt: '¿Qué dos colores tiene la bandera de la Unión Europea?', category: 'cultura', allowMultiple: true, correctColors: ['azul', 'amarillo'] },
  { id: 'multi-cultura-cruz-roja', prompt: '¿Qué dos colores tiene el emblema de la Cruz Roja?', category: 'cultura', allowMultiple: true, correctColors: ['rojo', 'blanco'] },
  { id: 'multi-cultura-onu', prompt: '¿Qué dos colores tiene la bandera de las Naciones Unidas?', category: 'cultura', allowMultiple: true, correctColors: ['azul', 'blanco'] },
  { id: 'multi-cultura-rgb', prompt: '¿Qué tres colores forman el modelo de luz RGB?', category: 'cultura', allowMultiple: true, correctColors: ['rojo', 'verde', 'azul'] },
  { id: 'multi-cultura-cmyk', prompt: '¿Qué cuatro colores, usando la paleta del juego, forman el modelo de impresión CMYK?', category: 'cultura', allowMultiple: true, correctColors: ['azul', 'rosa', 'amarillo', 'negro'] },
  { id: 'multi-cultura-gafas-3d', prompt: '¿Qué dos colores tienen las lentes de las gafas 3D anaglíficas clásicas?', category: 'cultura', allowMultiple: true, correctColors: ['rojo', 'azul'] },
  { id: 'multi-cultura-poste-barbero', prompt: '¿Qué tres colores tiene el poste de barbería tradicional?', category: 'cultura', allowMultiple: true, correctColors: ['rojo', 'blanco', 'azul'] },
  { id: 'multi-cultura-cebra', prompt: '¿Qué dos colores tiene el pelaje de una cebra?', category: 'cultura', allowMultiple: true, correctColors: ['negro', 'blanco'] },
  { id: 'multi-cultura-panda', prompt: '¿Qué dos colores tiene el pelaje de un panda gigante?', category: 'cultura', allowMultiple: true, correctColors: ['blanco', 'negro'] },
  { id: 'multi-cultura-mariquita', prompt: '¿Qué dos colores tiene la mariquita de siete puntos más reconocible?', category: 'cultura', allowMultiple: true, correctColors: ['rojo', 'negro'] },
  { id: 'multi-cultura-balon-futbol', prompt: '¿Qué dos colores tiene el balón de fútbol clásico de pentágonos y hexágonos?', category: 'cultura', allowMultiple: true, correctColors: ['blanco', 'negro'] },
];
